apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: side-car
    app.kubernetes.io/name: percona-xtradb-cluster
  name: side-car-proxysql
  ownerReferences:
    controller: true
    kind: PerconaXtraDBCluster
    name: side-car
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: mysql
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app.kubernetes.io/component: proxysql
    app.kubernetes.io/instance: side-car
    app.kubernetes.io/name: percona-xtradb-cluster
  sessionAffinity: None
  type: LoadBalancer
