apiVersion: pxc.percona.com/v1-6-0
kind: PerconaXtraDBCluster
metadata:
  name: monitoring
spec:
  secretsName: my-cluster-secrets
  sslSecretName: some-name-ssl
  pxc:
    size: 3
    image: -pxc
    resources:
      requests:
        memory: 500M
        cpu: 300m
    volumeSpec:
      persistentVolumeClaim:
        resources:
          requests:
            storage: 2Gi
    affinity:
      antiAffinityTopologyKey: none
  proxysql:
    enabled: true
    size: 1
    image: -proxysql
    resources:
      requests:
        memory: 500M
        cpu: 300m
    volumeSpec:
      persistentVolumeClaim:
        resources:
          requests:
            storage: 2Gi
    affinity:
      antiAffinityTopologyKey: none
  pmm:
    enabled: true
    image: -pmm
    serverHost: monitoring-service
